[package]
name = "zc-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
globset = { workspace = true }
jwalk = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
rusqlite = { workspace = true }
xxhash-rust = { workspace = true }
windows-sys = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
